### ISSUE TITLE
[Linux+GTX 1050Ti] Game fails to launch on world_rendering_completeness branch

### ISSUE THREAD

**Issue by KJP12** [Blaze4D-MC/Blaze4D#37]
Window shows for a split second then immediately crashes on trying runClient via Gradle.

OS: Arch Linux w/ 5.12.11-zen1-1-zen 
CPU: AMD FX-8320
Active GPU: NVIDIA GTX 1050 Ti w/ Driver 465.31

<details><summary>Crash report on <code>world_rendering_completeness</code> branch</summary>

```
[kjp12@home] ~/IdeaProjects/Blaze4D % JAVA_HOME=~/.jdks/adopt-openjdk-16.0.1 ./gradlew clean build runClient                                                                           [130]

> Configure project :
Fabric Loom: 0.9.25
Using project based jar storage

> Task :Rosella:compileKotlin
w: /home/kjp12/IdeaProjects/Blaze4D/Rosella/src/main/kotlin/me/hydos/rosella/render/model/ModelLoader.kt: (56, 29): Parameter 'scene' is never used

> Task :Rosella:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :compileJava
warning: Supported source version 'RELEASE_8' from annotation processor 'org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor' less than -source '16'
/home/kjp12/IdeaProjects/Blaze4D/src/main/java/me/hydos/blaze4d/mixin/texture/RenderSystemMixin.java:23: warning: Cannot find target method for @Inject in com.mojang.blaze3d.systems.RenderSystem
    @Inject(method = "setShaderTexture(ILnet/minecraft/class_2960;)V", at = @At("HEAD"), require = 0, cancellable = true) // ugly hack to get around mixin not remapping properly
    ^
warning: Supported source version 'RELEASE_8' from annotation processor 'org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor' less than -source '16'
3 warnings

> Task :remapSourcesJar
:remapping sources

> Task :runClient
[20:28:34] [main/INFO] (FabricLoader) Loading for game Minecraft 1.17.1
[20:28:34] [main/INFO] (Fabric|Loader) [FabricLoader] Loading 4 mods:
        - blaze4d@1.0.0-SNAPSHOT
        - fabricloader@0.11.6
        - java@16
        - minecraft@1.17.1
[20:28:35] [main/INFO] (mixin) SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/home/kjp12/.gradle/caches/modules-2/files-2.1/net.fabricmc/sponge-mixin/0.9.4+mixin.0.8.2/ef410951e94c7f4939cc74c86f8df371827818a4/sponge-mixin-0.9.4+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT
[20:28:35] [main/INFO] (Fabric|MixinBootstrap) Loaded Fabric development mappings for mixin remapper!
[20:28:35] [main/INFO] (mixin) Compatibility level set to JAVA_16
Completely ignored arguments: []
[20:28:37] [main/WARN] (FileUtil) Configuration conflict: there is more than one oshi.properties file on the classpath
[20:28:37] [main/WARN] (FileUtil) Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[20:28:48] [Render thread/INFO] (Minecraft) Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[20:28:50] [Render thread/ERROR] (Minecraft) Failed to verify authentication
com.mojang.authlib.exceptions.InvalidCredentialsException: Status: 401
        at com.mojang.authlib.exceptions.MinecraftClientHttpException.toAuthenticationException(MinecraftClientHttpException.java:56) ~[authlib-2.3.31.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilSocialInteractionsService.checkPrivileges(YggdrasilSocialInteractionsService.java:112) ~[authlib-2.3.31.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilSocialInteractionsService.<init>(YggdrasilSocialInteractionsService.java:42) ~[authlib-2.3.31.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createSocialInteractionsService(YggdrasilAuthenticationService.java:151) ~[authlib-2.3.31.jar:?]
        at net.minecraft.client.Minecraft.createSocialInteractions(Minecraft.java:670) [minecraft-1.17.1-project-@-mapped-loom.mappings-layered+hash.1125941807-v2.jar:?]
        at net.minecraft.client.Minecraft.<init>(Minecraft.java:429) [minecraft-1.17.1-project-@-mapped-loom.mappings-layered+hash.1125941807-v2.jar:?]
        at net.minecraft.client.main.Main.main(Main.java:179) [minecraft-1.17.1-project-@-mapped-loom.mappings-layered+hash.1125941807-v2.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
        at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
        at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
        at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
Caused by: com.mojang.authlib.exceptions.MinecraftClientHttpException: Status: 401
        at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:77) ~[authlib-2.3.31.jar:?]
        at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:47) ~[authlib-2.3.31.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilSocialInteractionsService.checkPrivileges(YggdrasilSocialInteractionsService.java:104) ~[authlib-2.3.31.jar:?]
        ... 13 more
[20:28:50] [Render thread/INFO] (Minecraft) Setting user: Player187
[20:28:50] [Render thread/INFO] (Minecraft) Backend library: LWJGL version 3.3.0 build 11
[20:28:53] [Render thread/WARN] (FileUtil) Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 7/16/21, 8:28 PM
Description: Initializing game

java.lang.RuntimeException: The application requested validation layers but they are not supported
        at me.hydos.rosella.Rosella.<init>(Rosella.java:55)
        at me.hydos.rosella.Rosella.<init>(Rosella.java:49)
        at com.mojang.blaze3d.platform.Window.handler$zzj000$initializeRosellaWindow(Window.java:636)
        at com.mojang.blaze3d.platform.Window.<init>(Window.java:119)
        at net.minecraft.client.renderer.VirtualScreen.newWindow(VirtualScreen.java:21)
        at net.minecraft.client.Minecraft.<init>(Minecraft.java:481)
        at net.minecraft.client.main.Main.main(Main.java:179)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
        at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
        at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
        at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
        at me.hydos.rosella.Rosella.<init>(Rosella.java:55)
        at me.hydos.rosella.Rosella.<init>(Rosella.java:49)
        at com.mojang.blaze3d.platform.Window.handler$zzj000$initializeRosellaWindow(Window.java:636)
        at com.mojang.blaze3d.platform.Window.<init>(Window.java:119)
        at net.minecraft.client.renderer.VirtualScreen.newWindow(VirtualScreen.java:21)
        at net.minecraft.client.Minecraft.<init>(Minecraft.java:481)

-- Initialization --
Details:
Stacktrace:
        at net.minecraft.client.main.Main.main(Main.java:179)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
        at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
        at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
        at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

-- System Details --
Details:
        Minecraft Version: 1.17.1
        Minecraft Version ID: 1.17.1
        Operating System: Linux (amd64) version 5.12.11-zen1-1-zen
        Java Version: 16.0.1, AdoptOpenJDK
        Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), AdoptOpenJDK
        Memory: 1765861752 bytes (1684 MiB) / 2608857088 bytes (2488 MiB) up to 8422162432 bytes (8032 MiB)
        CPUs: 8
        Processor Vendor: AuthenticAMD
        Processor Name: AMD FX(tm)-8320 Eight-Core Processor
        Identifier: AuthenticAMD Family 21 Model 2 Stepping 0
        Microarchitecture: unknown
        Frequency (GHz): 3.50
        Number of physical packages: 1
        Number of physical CPUs: 8
        Number of logical CPUs: 8
        Graphics card #0 name: GP107 [GeForce GTX 1050 Ti]
        Graphics card #0 vendor: NVIDIA Corporation (0x10de)
        Graphics card #0 VRAM (MB): 288.00
        Graphics card #0 deviceId: 0x1c82
        Graphics card #0 versionInfo: unknown
        Graphics card #1 name: RV710 [Radeon HD 4350/4550]
        Graphics card #1 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
        Graphics card #1 VRAM (MB): 256.00
        Graphics card #1 deviceId: 0x954f
        Graphics card #1 versionInfo: unknown
        Virtual memory max (MB): 38342.07
        Virtual memory used (MB): 33049.94
        Swap memory total (MB): 22283.00
        Swap memory used (MB): 9860.08
        JVM Flags: 1 total; -XX:+ShowCodeDetailsInExceptionMessages
        Launched Version: Fabric
        Backend library: LWJGL version 3.3.0 build 11
        Backend API: NO CONTEXT
        Window size: <not initialized>
        GL Caps: Using framebuffer using OpenGL 3.2
        GL debug messages: <disabled>
        Using VBOs: Yes
        Is Modded: Definitely; Client brand changed to 'fabric'
        Type: Client (map_client.txt)
        CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# /home/kjp12/IdeaProjects/Blaze4D/run/./crash-reports/crash-2021-07-16_20.28.53-client.txt

> Task :runClient FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':runClient'.
> Process 'command '/home/kjp12/.jdks/adopt-openjdk-16.0.1/bin/java'' finished with non-zero exit value 255

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 59s
19 actionable tasks: 19 executed
```
</details>

**Comment by hYdos** [comment]
We are not fixing bugs for user's at the moment. Don't expect it to work

**Comment by i509VCB** [comment]
@KJP12

Install the `vulkan-devel` package from pacman.
